### ISSUE TITLE
App froze in virtual bathroom

### ISSUE THREAD

**Issue by dnemaw** [GamesThatWork/BrushUpBuilds#15] opened 2024-03-29 19:09 UTC
The app froze when I was done with match game and ready to buy prizes. I couldn't tap anywhere on the screen.

**Comment by DovJacobson** [comment] 2024-04-01 08:54
cannot easily reproduce
v0.442 has changes that are intended to cure the issue
@dnemaw if it is now fixed please close
@ernstc2 please check if you can and close if you can

**Comment by ernstc2** [comment] 2024-04-01 11:51
seems to be cured, feel free to re-open if further related problems occur.

**Closed by ernstc2** 2024-04-01 11:51 UTC
